hevslc/JVM

- include/Slot.h
- src/Slot.cpp
> #58 - Uma primeira implementação para a classe Slot criada

- include/ClassFile.h
- include/Slot.h
- src/ClassFile.cpp
Closes #64  #53 
Estranho q esse erro da redeclaração do LONG não apareceu pra mim antes por isso tinha aceitado o pr do Slots, devo ter rodado a branch errada. De qlquer forma agr arrumei.
> fileName ok, redeclaration of 'LONG' fixed

- include/Slot.h
- src/Opcode.cpp
- posição OPCODEs sendo exibidas
- tableswitch opcode sendo exibido corretamente
> pos opcodes and tableswitch fix

- include/Slot.h
- src/AttributeInfo.cpp
Close #56 
Aproveitei e também imprimi attributesCount e exceptionTableLength.
> codeLength ok

- src/CpInfo.cpp
> bug Floating Point fixed

- include/AttributeInfo.h
- include/ClassFile.h
- include/Frame.h
- include/Instructions.h
- include/Interpreter.h
- src/AttributeInfo.cpp
- src/Frame.cpp
- src/Instructions.cpp
- src/Interpreter.cpp
- src/main.cpp
Iniciei Frame e Interpreter. Falta descomentar vetor de variáveis locais qndo estiver pronto.
Iniciei também função de execução.
Closes #75, Closes #74
> Frame interpreter #75 #74

- include/Frame.h
- include/Instructions.h
- src/Frame.cpp
- src/Instructions.cpp
- src/Interpreter.cpp
Instruções de retorno definem o fim da execução de um Frame. Detectando se tem um método main. Cada instrução adiciona 1 no PC pelo menos. Adicionado método no Frame.
> Aprimorando a execução da JVM

- include/Variables.h
- src/Variables.cpp
> Local variables

- include/Frame.h
- include/Instructions.h
- include/Utils.h
- src/Frame.cpp
- src/Instructions.cpp
- src/Interpreter.cpp
- src/Utils.cpp
Testei a execução para o arquivo de aritmética double.
> Criando execução para ldc2_w

- include/AttributeInfo.h
- include/Variables.h
- src/AttributeInfo.cpp
- src/Frame.cpp
> #84 - Fazendo a inicialização do vetor de variáveis locais

- src/Instructions.cpp
Testado com MultiArrayTest.class.
Close #86
> instrucoes iconst_<i>

- include/Definitions.h
- include/Instructions.h
- src/Instructions.cpp
Segui a documentação para as 3 instruções de novo array e para o heap (links na descrição da issue).
No caso do índice para Constant Pool, a [documentação](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.multianewarray) fala que a entrada deve ser do tipo classe, matriz ou tipo de interface. Portanto considerei as tags de classe e interface.
Foi testado com MultiArrayTest.class
Se quiser testar, basta descomentar as linhas com print. Ainda não trata exceções.
Não usei as bibliotecas do c++ _array_ pq precisa saber do tamanho em tempo de compiação, nem _vector_ pq é variável.
Close #87
> 87 arrays instructions

- include/Definitions.h
- src/Instructions.cpp
Correções: tamanho do array, acesso à referência.
Nova função offset(): calcula indice do array correspondente aos indices (i, j, k...). Ver [site](https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays).
Close #94
> correcao e aprimoramento multianewarray instr

- include/Slot.h
- src/Interpreter.cpp
- src/Slot.cpp
> get high and low double

- include/OperandStack.h
- include/Variables.h
- src/Instructions.cpp
- src/OperandStack.cpp
- src/Utils.cpp
- src/Variables.cpp
> Auxiliares adicionar/push de u8 em Variables/Operands

- include/Slot.h
- src/Instructions.cpp
- src/OperandStack.cpp
Botei referências pra uma string e pra um objeto qualquer.
> #118 - Atualização do Slot

- src/Instructions.cpp
> Revert "pop e pop2"

- include/Instructions.h
- include/Utils.h
- src/Instructions.cpp
- src/Utils.cpp
testado print e println.
testado getstatic.
Close #123 (getstatic)
> 117 invoker getstatic

- src/Instructions.cpp
> l2i, l2d e l2f add

- src/Instructions.cpp
Close #166 
- Add: iaload, faload, daload, baload, caload
- Correções: bastore, satores, castore, dastore, fastore, 
Os resultados para int_logico.class e vetor.class devem sair corretamente agora.
> correcao/add instr para int_logico e vetor .class
